# Generated by Django 5.0.6 on 2024-07-07 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lista', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blanco', models.IntegerField(default=0)),
                ('nulo', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('lista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lista.lista')),
            ],
        ),
    ]
