# Generated by Django 5.0.6 on 2024-07-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultado',
            name='blanco',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='nulo',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='total',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
