# Generated by Django 5.0.6 on 2024-07-06 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.IntegerField(choices=[('primero', 1), ('segundo', 2), ('tercero', 3), ('cuarto', 4), ('quinto', 5), ('sexto', 6)], default='1'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='paralelo',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E'), ('f', 'F')], default='a', max_length=1),
        ),
    ]
