# Generated by Django 5.1.1 on 2024-09-09 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0005_remove_estudiante_cedula_remove_estudiante_correo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.CharField(choices=[('Primero', 1), ('Segundo', 2), ('Tercero', 3), ('Cuarto', 4), ('Quinto', 5), ('Sexto', 6), ('Séptimo', 7)], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='curso',
            name='paralelo',
            field=models.CharField(choices=[('A', 'a'), ('B', 'b'), ('C', 'c'), ('D', 'd')], default='a', max_length=1),
        ),
    ]
