# Generated by Django 5.1.1 on 2024-09-09 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiante', '0006_alter_curso_nivel_alter_curso_paralelo'),
        ('lista', '0005_alter_lista_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dignidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dignidad', models.CharField(choices=[('Presidente', 'presidente'), ('Vicepresidente', 'vicepresidente'), ('Secretario/a', 'secretario/a'), ('Tesorero/a', 'tesorero/a'), ('Vocal-1', 'vocal-1'), ('Vocal-2', 'vocal-2')], default='presidente', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='listas')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiante.estudiante')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatos', to='lista.lista')),
                ('dignidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidato.dignidad')),
            ],
        ),
    ]
