# Generated by Django 5.0.6 on 2024-07-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0002_lista_propuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='nombre',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='lista',
            name='numero',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
