# Generated by Django 5.0.6 on 2024-07-16 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0003_alter_lista_nombre_alter_lista_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista',
            name='foto',
            field=models.ImageField(default='', upload_to='candidatos'),
            preserve_default=False,
        ),
    ]
