# Generated by Django 5.0.6 on 2024-07-17 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0004_lista_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='foto',
            field=models.ImageField(upload_to='listas'),
        ),
    ]
